version = 0.1

[default.global.parameters]
region = "ap-northeast-1"

[default.deploy.parameters]
stack_name = "try-form-sam"
resolve_s3 = false
s3_bucket = "try-bref-sam"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []


[prod.deploy]
[prod.deploy.parameters]
stack_name = "try-form-prod"
region = "ap-northeast-1"
resolve_s3 = false
s3_bucket = "try-bref-sam"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

parameter_overrides = [
  "AppEnv=prod",
  "AppDebug=false",
  "EmailFrom=no-reply@oppara.tv",
  "EmailAdmin=admin@oppara.tv",
  "MailSubjectAdmin=【お問い合わせ】がありました",
  "MailSubjectUser=【自動返信】お問い合わせありがとうございます",
  "LogRetentionInDays=3",
]
