version = 0.1

[default.global.parameters]
region = "ap-northeast-1"

[default.deploy.parameters]
stack_name = "try-form-sam"
resolve_s3 = false
s3_bucket = "ソースをアップロードするS3バケット名"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []


[prod.deploy]
[prod.deploy.parameters]
stack_name = "try-form-prod"
region = "ap-northeast-1"
resolve_s3 = false
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

parameter_overrides = [
  "AppEnv=prod",
  "AppDebug=false",
  "EmailFrom=エンベロープフロムメールアドレス",
  "EmailAdmin=管理者のメールアドレス",
  "MailSubjectAdmin=【お問い合わせ】がありました",
  "MailSubjectUser=【自動返信】お問い合わせありがとうございます",
  "CustomDomainName=カスタムドメイン",
  "HostedZoneName=ホストゾーン名",
  "CertificateArn=ACM証明書のARN",
  "RecaptchaType=v3",
  "RecaptchaSiteKey=reCAPTCHA サイトキー",
  "RecaptchaScoreThreshold=0.5"
]
